# Generated by Django 2.2.6 on 2019-11-09 06:19

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentdate',
            options={'verbose_name': 'Reserva por propiedad', 'verbose_name_plural': 'Reservas por propiedad'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reserva de cliente', 'verbose_name_plural': 'Reservas de cliente'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='img',
            field=models.ImageField(upload_to=renting.models.make_file_path),
        ),
    ]
