# Generated by Django 2.2.6 on 2019-11-09 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_auto_20191109_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='renting.Reservation'),
        ),
    ]
